services:
  - type: web
    name: OmelyApp
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    buildCommand: ""
    startCommand: ""
    env:
      DATABASE_URL: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12732571?allowPublicKeyRetrieval=true&useSSL=false
