package com.syqu.shop.service.impl;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.syqu.shop.domain.CheckoutUserInfor;
import com.syqu.shop.repository.CheckoutRepository;
import com.syqu.shop.service.CheckoutService;

import java.util.List;

@Service
public class CheckoutServiceImpl implements CheckoutService {

    private final CheckoutRepository checkoutRepository;

    @Autowired
    public CheckoutServiceImpl(CheckoutRepository checkoutRepository) {
        this.checkoutRepository = checkoutRepository;
    }

    @Override
    public CheckoutUserInfor saveUserInfo(CheckoutUserInfor userInfo) {
        return checkoutRepository.save(userInfo);
    }

    @Override
    public List<CheckoutUserInfor> getUserInfoByUsername(String username) {
        return checkoutRepository.findByUsername(username); // Retrieve user info by username
    }

    @Override
    public void deleteUserInfoByUsernameAndId(String username, Long id) {
        checkoutRepository.deleteByUsernameAndId(username, id); // Delete user info by username and ID
    }
    @Override
    public CheckoutUserInfor updateUserInfoById(Long id, CheckoutUserInfor updatedInfo) {
        if (updatedInfo == null) {
            throw new IllegalArgumentException("Updated information cannot be null");
        }
        if (id == null ){
             // Assuming the ID is autogenerated for new users
             updatedInfo.setId(null); // Ensure the ID is null to let the database auto-generate it
             return checkoutRepository.save(updatedInfo); // Insert new user info
        }
    
        // Check if the user exists by ID
        Optional<CheckoutUserInfor> existingUser = checkoutRepository.findById(id);
    
        if (existingUser.isPresent()) {
            // If user exists, update the fields
            CheckoutUserInfor userToUpdate = existingUser.get();
            userToUpdate.setFirstName(updatedInfo.getFirstName());
            userToUpdate.setLastName(updatedInfo.getLastName());
            userToUpdate.setEmail(updatedInfo.getEmail());
            userToUpdate.setMobileNo(updatedInfo.getMobileNo());
            userToUpdate.setAddress(updatedInfo.getAddress());
            userToUpdate.setDistrict(updatedInfo.getDistrict());
            userToUpdate.setCountry(updatedInfo.getCountry());
            userToUpdate.setCity(updatedInfo.getCity());
            userToUpdate.setZipCode(updatedInfo.getZipCode());
            userToUpdate.setUsername(updatedInfo.getUsername()); // Optional, if you allow username changes         
            return checkoutRepository.save(userToUpdate); // Save updated user info
        } else {
            // If user does not exist, insert a new user
            // Assuming the ID is autogenerated for new users
            updatedInfo.setId(null); // Ensure the ID is null to let the database auto-generate it
            return checkoutRepository.save(updatedInfo); // Insert new user info
        }
    }
}
