name: Build and Push JAR to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    # - name: Deploy to GitHub Pages
    #   run: |
    #     # Create a directory for deployment
    #     mkdir -p gh-pages

    #     # Copy the build artifacts to the deployment directory
    #     cp -R target/* gh-pages/

    #     # Go to the deployment directory
    #     cd gh-pages

    #     # Initialize a new Git repository
    #     git init
    #     git config user.name "ThuTanPhan0795"
    #     git config user.email "tanthu95bdkn@gmail.com"

    #     # Add remote and push to GitHub Pages
    #     git remote add origin git@github.com:ThuTanPhan0795/OmelyApp.git
    #     git checkout -b gh-pages
    #     git add .
    #     git commit -m "Deploy to GitHub Pages"
    #     git push -f origin gh-pages
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   - name: Copy JAR to master/target folder
      run: |
        # Create the target directory in the repository if it doesn't exist
        mkdir -p master/target

        # Copy the JAR file to the master/target directory
        cp target/shop-0.0.1-SNAPSHOT.jar master/target/

    - name: Commit and Push JAR to master branch
      run: |
        # Configure Git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Stash any unstaged changes to prevent conflicts
        git stash

        # Pull the latest changes from the remote master branch to avoid non-fast-forward issues
        git pull origin master --rebase

        # Pop (apply) the stashed changes
        git stash pop || true  # Prevent errors if there's nothing to stash

        # Force add the JAR file, ignoring .gitignore rules
        git add -f master/target/shop-0.0.1-SNAPSHOT.jar

        # Commit the change to master
        git commit -m "Add JAR file to master/target"

        # Push the changes to the master branch using GITHUB_TOKEN
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ThuTanPhan0795/OmelyApp.git master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}