name: Build and Push JAR to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Push JAR to master branch
      run: |
        # Check if a JAR file exists
        if ls target/*.jar 1> /dev/null 2>&1; then
          # Configure Git
          git config --global user.name "ThuTanPhan0795"
          git config --global user.email "tanthu95bdkn@gmail.com"

          # Check if the remote origin already exists, if not, add it
          if ! git remote | grep -q origin; then
            git remote add origin git@github.com:ThuTanPhan0795/OmelyApp.git
          fi

          # Force add the JAR file, bypassing .gitignore
          git add -f target/*.jar

          # Commit the changes
          git commit -m "Add built JAR file to /target folder"
          
          # Push changes to the master branch
          git push -f origin master
        else
          echo "No JAR file found to push."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}