name: Build and Push JAR to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build with Maven
      run: mvn clean package

    - name: Push JAR to master branch
      run: |
        # Check if a JAR file exists
        if ls target/*.jar 1> /dev/null 2>&1; then
          # Move JAR to the root of the repo (or desired location)
          mv target/*.jar ./

          # Configure Git
          git config --global user.name "ThuTanPhan0795"
          git config --global user.email "tanthu95bdkn@gmail.com"

          # Stage the JAR file
          git add *.jar
          git commit -m "Add built JAR file"
          git push origin master
        else
          echo "No JAR file found to push."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}