- name: Push JAR to master branch
  run: |
    # Check if a JAR file exists
    if ls target/*.jar 1> /dev/null 2>&1; then
      # Move JAR to the root of the repo (or desired location)
      mv target/*.jar ./

      # Configure Git
      git config --global user.name "ThuTanPhan0795"
      git config --global user.email "tanthu95bdkn@gmail.com"

      # Initialize a new Git repository
      git init
      git remote add origin git@github.com:ThuTanPhan0795/OmelyApp.git
      
      # Stage the JAR file
      git add *.jar
      git commit -m "Add built JAR file"
      
      # Push changes to the master branch
      git push -f origin master
    else
      echo "No JAR file found to push."
    fi
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}