name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Create gh-pages directory
      run: mkdir -p gh-pages

    - name: Check if target directory exists
      run: if [ -d "target" ]; then echo "Target directory exists."; else echo "Target directory does not exist."; exit 1; fi

    - name: Copy build artifacts to the gh-pages directory
      run: cp -R target/* gh-pages/

    - name: Deploy to GitHub Pages
      run: |
        cd gh-pages
        git init
        git config user.name "ThuTanPhan0795"
        git config user.email "tanthu95bdkn@gmail.com"
        git remote add origin git@github.com:ThuTanPhan0795/OmelyApp.git
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push -f origin gh-pages
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
