name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to GitHub Pages
      run: |
        # Create a directory for deployment
        mkdir -p gh-pages

        # Copy the build artifacts to the deployment directory
        cp -R target/* gh-pages/

        # Go to the deployment directory
        cd gh-pages

        # Initialize a new Git repository
        git init
        git config user.name "ThuTanPhan0795"
        git config user.email "tanthu95bdkn@gmail.com"

        # Add remote and push to GitHub Pages
        git remote add origin git@github.com:ThuTanPhan0795/OmelyApp.git
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push -f origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
